baseURL = "https://blog-ijx8.onrender.com"
languageCode = "en-us"
title = ""
theme = "cactus"


[params]

  description = "Interpretability, samadhi practice and general wellbeing. Prev research eng @ Adobe, mle @ Meta"
[[params.social]]
  name = "linkedin"
  link = "https://www.linkedin.com/in/oana-florescu-97996716a/"

[[params.social]]
  name = "twitter"
  link = "https://twitter.com/0xflores"

[[params.social]]
  name = "youtube"
  link = "https://www.youtube.com/channel/UCrrQ55QjxXEDbJ4ojOjXvTw" # no need for "mailto:" at the start
